#!/bin/bash

# Hello Nightmare
# Copyright (C) 2018-2019  Joao Eriberto Mota Filho <eriberto@eriberto.pro.br>
#
#           DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                   Version 2, December 2004
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
# 
#           DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#  TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
# 0. You just DO WHAT THE FUCK YOU WANT TO.
#
# --------------------------------------------------------------
# ----> IF YOU NEED, YOU CAN USE THIS PROGRAM UNDER BSD LICENSE.
# --------------------------------------------------------------

VERSION=1.0

function help() {
    echo -e "\nHello Nightmare $VERSION"
    echo -e "\nUsage:"
    echo -e "\t-1 Show message number 1."
    echo -e "\t-2 Show message number 2."
    echo -e "\t-h Show this help."
    echo -e "\t-v Show version."
    exit 1
}

[ "$1" = "-1" ] && { echo -e "\nI am your nightmare!"; exit 0; }

[ "$1" = "-2" ] && { echo -e "\n\033[0;31mI am \033[0;32myour \033[0;33mworst \033[1;33mnightmare!\033[0m"; exit 0; }

[ "$1" = "-v" ] && { echo "Hello Nightmare $VERSION"; exit 1; }

help
